name: Example Workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: eslint-action@v2
        with:
          files: "src/**"
          extensions: ".js"
          quiet: "false"
